# Spring Boot settings
server.port=8080

# MySQL settings
spring.datasource.url=jdbc:mysql://localhost:3306/chat_db
spring.datasource.username=root
spring.datasource.password=gabi2004
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Disable ORM (Hibernate)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# Session configuration
server.servlet.session.timeout=30m
server.servlet.session.cookie.http-only=true